export const start_btn = document.getElementById("start_btn")
export const quiz_box = document.getElementById("quiz_box")
export const result_box = document.getElementById("result_box")
export const restart_btn = result_box.getElementById("restart_btn")
export const option_list = document.getElementById("option_list")
export const timeText = document.getElementById("time_left")
export const timeCount = document.getElementById("timer_sec")
export const theme_btn = document.getElementById("theme_btn")